#####################################################
#                                                   #
# parameters usually adjusted by the user each time #
#                                                   #
#####################################################
#
# workflow base directory
WFLOWDIR:  "/home/l848a/repos/VirusHunterGatherer"
#
# list with SRA accessions (empty string to use user-specified data)
ACCLIST:   "/home/l848a/sp4/branch3/Flaviviridae_SRAs_to_assemble/Flaviviridae-Mammals-RNA-newJan2023.txt"
#
# directory with fastq files
FASTQDIR:  "/home/l848a/sp4/branch3/Flaviviridae_SRAs_to_assemble/flavi_fastq"
#
# group of viruses to search for (RNAviruses, smallDNAviruses, largeDNAviruses)
VIRFAM:    "RNAviruses"
#
# name of project folder
PROJECTID: "flavi_results"
#
# number of threads to use for analysis of individual datasets
THREADS:   6
#
# assembler to be used for seed-based assembly using Genseed-HMM
ASSEMBLER: "cap3"
#
# flag to specify whether or not SRA data is to be analyzed
ISSRA:     1
#
# flag to enbable mapping against human genome; only recommended when analysing human samples
MAPHG38:   0
#
#####################################################
#                                                   #
# parameters usually adjusted by the user only once #
#                                                   #
#####################################################
#
# base directoy where results are saved
BASEDIR:   "/home/l848a/sp4/branch3/Flaviviridae_SRAs_to_assemble"
#
# blast database used for 1st filtering step against contaminant sequences
DBFILTER:  "/home/l848a/vhvg_databases/filter/filter"
#
# blast database used for 2nd filtering step against non-viral RefSeq
DBREFSEQ:  "/home/l848a/vhvg_databases/refseq_protein_v4/refseq_protein"
#
# blast database used for 3rd filtering step against viral RefSeq
DBVIRAL:   "/home/l848a/vhvg_databases/viral_genomic/riboviria_no_pararnavirae_genomic"
#
# list of viral accessions in RefSeq
ACCSVIRAL: "/home/l848a/vhvg_databases/viral_protein/viral_protein.acc_list"
#
# flag to enbable debugging mode
DEBUGMODE: 0
#

