# 
# NOTE: Replace <full_path_to_directory> with the path to the directory where you cloned the repository.
# By default, this is the location of the VirusHunterGatherer folder on your system.
#
#
#####################################################
# Workflow path
#####################################################
#
# workflow directory (path to the repository)
WFLOWDIR:  "<full_path_to_directory>/VirusHunterGatherer"
#
#
#####################################################
# Input data
#####################################################
#
# is SRA data to be analyzed (1 = yes, 0 = no)
ISSRA:     1
#
# list of SRA accessions (use "" to skip and provide your own data below)
ACCLIST:   "<full_path_to_directory>/VirusHunterGatherer/3_examples/SRA_n3_acclist.txt"
#
# directory with your fastq files (or location for downloaded from SRA fastq files)
FASTQDIR:  "<full_path_to_directory>/SRA_n3_test"
#
#
#####################################################
# Output configuration
# Final output path will be:
# <BASEDIR>/<VIRFAM>/<PROJECTID>
#####################################################
#
# base directory where results are saved
BASEDIR:   "<full_path_to_directory>/vhvg_results"
#
# virus group to search for (e.g., RNAviruses, smallDNAviruses, largeDNAviruses, ...)
# corresponds to an HMM profile in the `2_profiles` directory; custom HMM profiles should also be placed there
VIRFAM:    "RNAviruses"
#
# name of project folder
PROJECTID: "test_SRA_n3"
#
#
#####################################################
# Databases and filtering
#####################################################
#
# blast database used for filtering against contaminant sequences
DBFILTER:  "<full_path_to_directory>/VirusHunterGatherer/4_databases/filter/filter"
#
# blast database used for filtering against non-viral RefSeq proteins
DBREFSEQ:  "<full_path_to_directory>/VirusHunterGatherer/4_databases/refseq_protein/refseq_protein"
#
# blast database of viral RefSeq genomes used for annotation of viral contigs
DBVIRAL:   "<full_path_to_directory>/VirusHunterGatherer/4_databases/viral_genomic/viral_genomic"
#
# list of viral protein accessions used for annotation of viral contigs
ACCSVIRAL: "<full_path_to_directory>/VirusHunterGatherer/4_databases/viral_protein/viral_protein.acc_list"
#
# enable filtering against non-viral RefSeq proteins (1 = yes, 0 = no)
ENABLE_FILTER_3: 0
#
#
#####################################################
# Workflow execution parameters
#####################################################
#
# run only VirusHunter, but not VirusGatherer (1 = yes, 0 = no)
ONLYHUNTER: 0
#
# assembler to be used for seed-based assembly using Genseed-HMM
ASSEMBLER: "cap3"
#
# number of threads to use for analysis of individual datasets
THREADS:   6
#
# enable mapping against human genome (1 = yes, 0 = no);
# only recommended when analysing human samples
MAPHG38:   0
#
# enable debugging mode (1 = yes, 0 = no)
# when enabled, intermediate files are not removed and can consume a lot of disk space
DEBUGMODE: 0
#
