#####################################################
#                                                   #
# parameters usually adjusted by the user each time #
#                                                   #
#####################################################
#
# list with SRA accessions (empty string to use user-specified data)
ACCLIST:   "/home/lauber/workflows/01_VirusHunterGatherer/3_examples/SRA_n1_acclist.txt"
#
# directory with fastq files
FASTQDIR:  "/data/tests/SRA_n1_test"
#
# group of viruses to search for (RNAviruses, smallDNAviruses, largeDNAviruses)
VIRFAM:    "RNAviruses"
#
# name of project folder
PROJECTID: "test_SRA_n1"
#
# number of threads to use for analysis of individual datasets
THREADS:   6
#
# flag to enbable mapping against human genome; only recommended when analysing human samples
MAPHG38:   0
#
#####################################################
#                                                   #
# parameters usually adjusted by the user only once #
#                                                   #
#####################################################
#
# workflow base directory
WFLOWDIR:  "/home/lauber/workflows/01_VirusHunterGatherer"
#
# base directoy where results are saved
BASEDIR:   "/data/virushunter"
#
# blast database used for 1st filtering step against contaminant sequences
DBFILTER:  "/data/db/RefSeq/filter/filter"
#
# blast database used for 2nd filtering step against non-viral RefSeq
DBREFSEQ:  "/data/db/RefSeq/refseq_protein/refseq_protein"
#
# blast database used for 3rd filtering step against viral RefSeq
DBVIRAL:   "/data/db/RefSeq/viral_genomic/viral_genomic"
#
# list of viral accessions in RefSeq
ACCSVIRAL: "/data/db/RefSeq/viral_protein/viral_protein.acc_list"
#
# flag to enbable debugging mode
DEBUGMODE: 0
#

